### ISSUE TITLE
Хук before добавляет в тип result лишний undefined

### ISSUE THREAD

**Issue by dj-stormtrooper** [descript-org/descript3#14]
В рантайме `return undefined` внутри `before` скипается и никак не аффектит `result`, но в тайпинге для `result` добавляется лишний `undefined`

пример

https://www.typescriptlang.org/play/index.html#code/JYWwDg9gTgLgBAEwKZwGZQiOByZBnAYymDBmwG4AoS5AOggCMArJAmACgG9K5e4GANhAIBrAFxxOAXwA0PPhFLAIAOzwTufLfySpoSCVzhgAhlBMg8cKRuNmLeAPy29ECQwgQBSEyutSASjgAXgA+SXltbWBUOHZTc0tHWlcgzSiM3igkGABXKD9sVwpIzOtqMr5svILSrVk6vhNUGCQoQwCJPBhiFQBzAB8VXJAGNpDwgFY5erlAoA

**Comment by pasaran** [comment]
Ну тут все более-менее правильно и понятно.
Тип `Result` блока должен откуда-то вывестись. Он может вывестись из `after`, а может из `before`. И вроде никак на это я повлиять не могу. Ты ждешь, что он выведется из `after`, а он, похоже, выводится из `before`.
Я хз как тут быть пока.

Кажется, что нужно смотреть сюда https://github.com/pasaran/descript3/issues/12.
И явно задавать тип блока через дженерик.

**Comment by pasaran** [comment]
Посмотри в docs/typescript-examples/options.ts, вроде у меня ок с before все.
