### ISSUE TITLE
de.func неправильно выводит тип, если вернуть Promise

### ISSUE THREAD

**Issue by doochik** [descript-org/descript3#17]
Пример: https://www.typescriptlang.org/play?ssl=1&ssc=1&pln=19&pc=1#code/JYWwDg9gTgLgBAEwKZwGZQiOByZBnAYymDBmwG4AoS4AOxiSlQEMCUARZmZuAb0riC0ECAC44eGMVoBzKgF9qBCLUlwARgBsIBANZwAvIiQA6VAFdaBABT8hG7XvHWAlIYB8fAfaHLV8KCQ8c00YcU5uQz5hMRx1ZihsOHkqHyEAenS4QJhzKFpsoJCYVLTC3Py4AAUMEGA8U0C8CE0ANyRrJuKXUsF5ABpvQQhSYBU8cTsy5lQGKGdeQuDQ5LcDTymyoRy8gq7QsxFenwGh5MH5HsogA

```ts
import de from 'descript';

interface Data {
    foo: string;
}

const block = de.func({
    block: () => {
        const result: Data = { foo: 'bar' };
        // return result;
        return Promise.resolve(result);
    },
    options: {
        after: ({ result }) => {
            return result.foo;
        },
    },
});
```

Баг в том, что в `after()` `result` вычисляется как `Promise<Data>`, а должен быть `Data`

**Comment by pasaran** [comment]
Раскомментил строчку с `Promise< Result >` в 3.0.27.
